### PR TITLE
allow to define target specific dependencies

### LINKED ISSUE #33: Support target specific dependencies
At `librsvg` we have a dependency on `pangoft2` and `fontconfig`, but not if you are building for Windows. I'd like to be able to express such a target-specific dependency using `system_deps`. Is that already possible, is such a feature planned?

### PR DESCRIPTION
**Pull request by gdesmott**
Fix #33

### CODE REVIEW

**Comment by svenfoo** [comment]
This doesn't work so well for the use case of `librsvg`. We would like to be able to express that `pangoft2` and `fontconfig` are required dependencies for all platforms but win32.

I think what would work better is to stick more closely to the syntax that Cargo uses for platform specific configurations. Something like the following would certainly be somewhat more complex, but afaics it should allow all sorts of platform-specific dependencies to be expressed:

```
[package.metadata.system-deps]
libxml2 = { name = "libxml-2.0", version = "2.9" }
pangocairo = "1.38"

[package.metadata.system-deps.'cfg(windows)']
fontconfig = { version = "1.7", optional = true }
pangoft2 = { version = "1.38", optional = true }

[package.metadata.system-deps.'cfg(not(windows))']
fontconfig = { version = "1.7" }
pangoft2 = { version = "1.38" }

```

**Comment by jnqnfe** [comment]
I'd agree that supporting such `cfg()` based conditions would be the ideal means of capturing platform conditional data.

**Comment by gdesmott** [comment]
Looks like there is a [cfg!](https://doc.rust-lang.org/std/macro.cfg.html), I suppose we could use that to implement such feature.

**Comment by gdesmott** [comment]
Actually `cfg!` does not allow me to pass a string, so I think I'd have to use something like [parse_cfg](https://crates.io/crates/parse_cfg) or [cfg-expr](https://crates.io/crates/cfg-expr).

**Comment by gdesmott** [comment]
@svenfoo @jnqnfe : I implemented just that thanks to the awesome [cfg-expr](https://github.com/EmbarkStudios/cfg-expr/) and their great maintainers which have been very helpful improving the crate to fit my needs.

Can you please give it a shot?

**Comment by svenfoo** [comment]
Wow, that's exactly the syntax that I proposed, and it seems to work nicely. That's awesome! 😍

I have updated the [feature branch in librsvg](https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/472) with this solution.

**Comment by gdesmott** [comment]
Great! It's been quite easy to implement actually, thanks to the `cfg-expr` crate.

I just released `3.1.0` with this new feature so you should be good for librsvg.

**Comment by svenfoo** [comment]
Thanks a lot! We are now using this in `librsvg` master branch and this brings us one step closer to the goal of dropping the autoconf/automake based build system in favor of using `cargo` only.

**Pull request merged**
