### PR TITLE
add env variables to statically link libraries

### LINKED ISSUE #40: Support static linking
I'm currently trying to figure out how to support static linking of libraries.
It seems that's a rather tricky task, as `pkg-config` doesn't seem to provide a way (at least `pub`) to check if the library is static (via `pkg_config::Config::probe`).

I've seen that `pkg_config::Config::cargo_metadata` is set to false everywhere where it is used (as this is apparently done in this lib), Is there a reason for not using `pkg-config`'s `cargo_metadata`? As setting it to `true` does have the desired effect of hinting cargo that the desired lib is static (and not printing it in this lib).

### PR DESCRIPTION
**Pull request by gdesmott**
Fix #40

### CODE REVIEW

**Review by lu-zero — APPROVED** [review]
It should work, probably adding mock .pc with `Requires.private` and `Libs.private` to test it might be a good idea.

Thank you a lot for the feature :)

**Review by Luni-4 — APPROVED** [review]
This is fine for me! Thanks a lot for your implementation! :)

After this PR will land, could you please release a new version?

**Comment by gdesmott** [comment]
I just released 3.2.0 with this feature. :)

**Comment by Luni-4** [comment]
Thanks a lot! :)

**Pull request merged**
